# Generated by Django 5.0.2 on 2024-03-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
